#!/usr/bin/env bash
#
# PortLink one-command local setup.
#   clone → npm install → npm run setup → npm run dev
#
# Brings a fresh checkout from zero to a running local stack:
#   1. Verifies Docker + the Supabase CLI are available
#   2. Initializes Supabase if needed and starts the local stack
#   3. Writes .env.local with the local API URL + keys (only if missing)
#   4. Applies all migrations and seeds the device fleet (supabase db reset)
#
# Re-running is safe: if .env.local already exists it is left untouched
# (your values are never overwritten) and the script just prints the keys.
#
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
echo -e "${BOLD}⚓ PortLink — local setup${NC}\n"

# --- 1. Prerequisites -------------------------------------------------------
command -v docker &>/dev/null || { echo -e "${RED}Docker not installed.${NC} Install Docker Desktop: https://www.docker.com/"; exit 1; }
docker info &>/dev/null 2>&1 || { echo -e "${RED}Docker is not running.${NC} Open Docker Desktop and wait for it to start, then re-run."; exit 1; }
command -v supabase &>/dev/null || { echo -e "${RED}Supabase CLI not installed.${NC} Install: brew install supabase/tap/supabase  (or: npm install -g supabase)"; exit 1; }
echo -e "${GREEN}✓${NC} Docker is running"
echo -e "${GREEN}✓${NC} Supabase CLI installed"

# --- 2. Init + start --------------------------------------------------------
if [ ! -f "supabase/config.toml" ]; then
    echo -e "\n${BOLD}Initializing Supabase...${NC}"
    supabase init
fi

echo -e "\n${BOLD}Starting local stack${NC} (first run downloads container images — this can take a few minutes)..."
supabase start

# --- 3. Environment file ----------------------------------------------------
if [ -f ".env.local" ]; then
    echo -e "\n${YELLOW}.env.local already exists — leaving it untouched.${NC}"
    echo "  If you need the current local keys, run: supabase status"
else
    echo -e "\n${BOLD}Writing .env.local from local Supabase credentials...${NC}"
    # `supabase status -o env` emits KEY="value" lines we can read directly.
    eval "$(supabase status -o env 2>/dev/null)"
    {
        echo "# Generated by scripts/setup-local-supabase.sh for LOCAL development."
        echo "# Safe to delete and regenerate. Never commit this file."
        echo ""
        echo "NEXT_PUBLIC_SUPABASE_URL=${API_URL}"
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}"
        echo "SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}"
        echo ""
        echo "# Local dev defaults — fine to leave as-is for local work."
        echo "# Test the ingestion webhook / cron endpoints with these shared secrets."
        echo "SENDGRID_INBOUND_PARSE_WEBHOOK_SECRET=dev-webhook-secret"
        echo "CRON_SECRET=dev-cron-secret"
        echo ""
        echo "# Twilio (SMS) is disabled locally — leave blank unless testing alerts."
        echo "TWILIO_ACCOUNT_SID="
        echo "TWILIO_AUTH_TOKEN="
        echo "TWILIO_FROM_NUMBER="
    } > .env.local
    echo -e "${GREEN}✓${NC} .env.local written"
fi

# --- 4. Schema + seed -------------------------------------------------------
echo -e "\n${BOLD}Applying migrations and seeding the device fleet...${NC}"
supabase db reset

# --- Done -------------------------------------------------------------------
echo -e "\n${GREEN}${BOLD}Setup complete!${NC}\n"
echo -e "  Start the app:        ${BOLD}npm run dev${NC}    → http://localhost:3000"
echo -e "  Supabase Studio (DB): http://127.0.0.1:54323"
echo -e "  Inbucket (auth mail): http://127.0.0.1:54324"
echo ""
echo -e "  ${BOLD}Sign in:${NC} use a magic link — submit your email on the login page,"
echo -e "  then open the message in Inbucket to follow the link."
echo ""
echo -e "  ${BOLD}Handy commands:${NC}"
echo -e "    supabase status        — URLs + keys"
echo -e "    supabase stop          — stop the local stack"
echo -e "    npm run db:reset       — wipe + re-apply migrations and seed"
echo -e "    npm run db:types       — regenerate src/types/database.ts from the local schema"
echo ""
echo -e "  ${YELLOW}Deploying to production?${NC} See DEPLOYMENT.md."
